###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [6]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [7]:
get_state(4)

[[14  1  9  3]
 [ 4  0 11  7]
 [ 6  2  8 10]
 [15  5 13 12]]


[14, 1, 9, 3, 4, 0, 11, 7, 6, 2, 8, 10, 15, 5, 13, 12]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [8]:
def count_inversion(s):
    count = 0
    for i in range(len(s)):    
        for j in range(i+1,len(s)):        
            if s[j]!=0 and s[i] > s[j]: count += 1
    return count

In [13]:
s = get_state(4)
print(s)
print(count_inversion(s))

[[ 6  0 11  9]
 [ 4  1  2  8]
 [13  3  5 10]
 [15 12 14  7]]
[6, 0, 11, 9, 4, 1, 2, 8, 13, 3, 5, 10, 15, 12, 14, 7]
38


# **Find blank row**

In [10]:
# find row position of the blank tile
def get_blank_row(s):
  # define here


SyntaxError: ignored

# Solvability Rules

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
  N = ?
  I = ?#call function here
  R = ?#call function here
  # decide solvability
  


In [ ]:
S = get_state(4)
isSolvable(S)
